### ISSUE TITLE
Incomatible with Divi-Layout

### ISSUE THREAD

**Issue by LarsK1** [litespeedtech/lscache_wp#202]
Using Divi the following error occurs:
```
[17-Mar-2020 07:52:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method LiteSpeed\API::debug() in /home/steuerb1/LarsKusch/WordPress/wp-content/plugins/litespeed-cache/src/api.cls.php:136
Stack trace:
#0 /home/steuerb1/LarsKusch/WordPress/wp-content/plugins/litespeed-cache/thirdparty/divi-theme-builder.cls.php(30): LiteSpeed\API::disable_all('divi edit mode')
#1 /home/steuerb1/LarsKusch/WordPress/wp-includes/class-wp-hook.php(288): LiteSpeed\Thirdparty\Divi_Theme_Builder::preload('')
#2 /home/steuerb1/LarsKusch/WordPress/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#3 /home/steuerb1/LarsKusch/WordPress/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/steuerb1/LarsKusch/WordPress/wp-content/plugins/litespeed-cache/src/core.cls.php(134): do_action('litespeed_init')
#5 /home/steuerb1/LarsKusch/WordPress/wp-includes/class-wp-hook.php(288): LiteSpeed\Core->init('')
#6 /home/steuerb1/LarsKusch/WordPress/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#7 /home/steuerb1/LarsKusch/Word in /home/steuerb1/LarsKusch/WordPress/wp-content/plugins/litespeed-cache/src/api.cls.php on line 136
```

**Comment by hailite** [comment]
Fixed in https://github.com/litespeedtech/lscache_wp/commit/c9a8433c5aa69ea2bf2f60d4d89dbb35d1c76173

Thanks.
