### ISSUE TITLE
PHP Fatal error:  Unsupported argument type passed to WP_CLI::error_to_string(): 'NULL' in phar

### ISSUE THREAD

**Issue by splaquet** [litespeedtech/lscache_wp#410]
My apologies if I'm overlooking an obvious solution, but I've recently started seeing this error in my logs.  I'd first guess that it's isolated to the site, but I'm seeing it across multiple sites on different servers.

LSCache v4.4.3 

```
[22-Oct-2021 07:00:34 UTC] PHP Warning:  strip_tags() expects parameter 1 to be string, array given in /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php on line 370
[22-Oct-2021 07:00:34 UTC] PHP Stack trace:
[22-Oct-2021 07:00:34 UTC] PHP   1. {main}() /usr/local/bin/wp:0
[22-Oct-2021 07:00:34 UTC] PHP   2. include() /usr/local/bin/wp:4
[22-Oct-2021 07:00:34 UTC] PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:11
[22-Oct-2021 07:00:34 UTC] PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
[22-Oct-2021 07:00:34 UTC] PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:77
[22-Oct-2021 07:00:34 UTC] PHP   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:23
[22-Oct-2021 07:00:34 UTC] PHP   7. WP_CLI\Runner->run_command_and_exit() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1194
[22-Oct-2021 07:00:34 UTC] PHP   8. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:422
[22-Oct-2021 07:00:34 UTC] PHP   9. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:399
[22-Oct-2021 07:00:34 UTC] PHP  10. call_user_func:{phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491}() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
[22-Oct-2021 07:00:34 UTC] PHP  11. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure:phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:97-104}() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
[22-Oct-2021 07:00:34 UTC] PHP  12. call_user_func:{phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100}() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100
[22-Oct-2021 07:00:34 UTC] PHP  13. Cron_Event_Command->run() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100
[22-Oct-2021 07:00:34 UTC] PHP  14. Cron_Event_Command::run_event() phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php:265
[22-Oct-2021 07:00:34 UTC] PHP  15. do_action_ref_array() phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php:343
[22-Oct-2021 07:00:34 UTC] PHP  16. WP_Hook->do_action() /home/domain.com/public_html/wp-includes/plugin.php:518
[22-Oct-2021 07:00:34 UTC] PHP  17. WP_Hook->apply_filters() /home/domain.com/public_html/wp-includes/class-wp-hook.php:327
[22-Oct-2021 07:00:34 UTC] PHP  18. LiteSpeed\Img_Optm::cron_auto_request() /home/domain.com/public_html/wp-includes/class-wp-hook.php:303
[22-Oct-2021 07:00:34 UTC] PHP  19. LiteSpeed\Img_Optm->new_req() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/img-optm.cls.php:336
[22-Oct-2021 07:00:34 UTC] PHP  20. LiteSpeed\Img_Optm->_send_request() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/img-optm.cls.php:465
[22-Oct-2021 07:00:34 UTC] PHP  21. LiteSpeed\Cloud::post() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/img-optm.cls.php:642
[22-Oct-2021 07:00:34 UTC] PHP  22. LiteSpeed\Cloud->_post() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php:579
[22-Oct-2021 07:00:34 UTC] PHP  23. LiteSpeed\Cloud->_maybe_cloud() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php:594
[22-Oct-2021 07:00:34 UTC] PHP  24. LiteSpeed\Admin_Display::error() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php:552
[22-Oct-2021 07:00:34 UTC] PHP  25. LiteSpeed\Admin_Display::add_notice() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php:356
[22-Oct-2021 07:00:34 UTC] PHP  26. strip_tags() /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php:370
[22-Oct-2021 07:00:34 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: Unsupported argument type passed to WP_CLI::error_to_string(): 'NULL' in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php:1051
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php(865): WP_CLI::error_to_string()
#1 /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php(372): WP_CLI::error()
#2 /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php(356): LiteSpeed\Admin_Display::add_notice()
#3 /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php(552): LiteSpeed\Admin_Display::error()
#4 /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php(594): LiteSpeed\Cloud->_maybe_cloud()
#5 /home/domain.com/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php(579): LiteSpeed\Cloud->_post()
#6 /home/domain.com/public_html/wp-content/plugins/litespeed-cache in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php on line 1051
```

**Comment by DeanMarkTaylor** [comment]
@hi-hai could I get you to re-open this issue, I'm experiencing the same problem.

I have a slightly more detailed stack trace for you:
```
Warning: strip_tags() expects parameter 1 to be string, array given in /home/xxx/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php on line 370
Fatal error: Uncaught InvalidArgumentException: Unsupported argument type passed to WP_CLI::error_to_string(): 'NULL' in phar:///usr/bin/wp-source/vendor/wp-cli/wp-cli/php/class-wp-cli.php:1042
Stack trace:
#0 phar:///usr/bin/wp-source/vendor/wp-cli/wp-cli/php/class-wp-cli.php(856): WP_CLI::error_to_string(NULL)
#1 /home/xxx/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php(372): WP_CLI::error(NULL, false)
#2 /home/xxx/public_html/wp-content/plugins/litespeed-cache/src/admin-display.cls.php(356): LiteSpeed\Admin_Display::add_notice('notice notice-e...', NULL, false, false)
#3 /home/xxx/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php(552): LiteSpeed\Admin_Display::error(Array)
#4 /home/xxx/public_html/wp-content/plugins/litespeed-cache/src/cloud.cls.php(594): LiteSpeed\Cloud->_maybe_cloud('img_optm-new_re...')
#5 /home/xxx/public_html/wp-content/plugins/litespeed-cache/src/cloud.c in phar:///usr/bin/wp-source/vendor/wp-cli/wp-cli/php/class-wp-cli.php on line 1042
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
```

This leads me to believe the following line should be changed:
https://github.com/litespeedtech/lscache_wp/blob/eae146404951e39354ee770dfad3d1fa1f5736e7/src/cloud.cls.php#L552

I believe it should be changed to:
```
Admin_Display::error( $msg );
```

**Comment by hi-hai** [comment]
Confirmed. It only happen when using CLI and meet error. That is why I didn't notice it. Will give fix soon.
