### ISSUE TITLE
Crawler Settings error notice: Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array

### ISSUE THREAD

**Issue by oldrup** [litespeedtech/lscache_wp#590]
Hey. Got this error on a single on of my WP 6.4 sites on the same host.. PHP 8.1:

`Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /home/removed/wp-content/plugins/litespeed-cache/src/crawler.cls.php:100 Stack trace: #0 /home/removed/wp-content/plugins/litespeed-cache/src/crawler.cls.php(100): in_array() #1 /home/removed/wp-content/plugins/litespeed-cache/tpl/crawler/summary.tpl.php(169): LiteSpeed\Crawler->is_active() #2 /home/removed/wp-content/plugins/litespeed-cache/tpl/crawler/entry.tpl.php(44): require('/home/sustain2/...') #3 /home/removed/wp-content/plugins/litespeed-cache/src/admin-display.cls.php(658): require_once('/home/sustain2/...') #4 /home/removed/wp-includes/class-wp-hook.php(324): LiteSpeed\Admin_Display->show_crawler() #5 /home/removed/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #6 /home/removed/wp-includes/plugin.php(517): WP_Hook->do_action() #7 /home/removed/wp-admin/admin.php(259): do_action() #8 {main} thrown in /home/removed/wp-content/plugins/litespeed-cache/src/crawler.cls.php on line 100

There has been a critical error on this website. Please check your site admin email inbox for instructions.`

Can't say if it's something regarding the install, but I've tried:

- disabled all other plugins
- reset LiteSpeed plugin settings.
- uninstalled LiteSpeed plugin and reinstalled.

Any hints would be appreciated; I hate having an error like that linger even though I don't really need the crawler.

![image](https://github.com/litespeedtech/lscache_wp/assets/17141205/ae4aaabb-b381-4593-b027-863b7be1139f)

**Comment by hi-hai** [comment]
Can you try latest dev?

**Comment by oldrup** [comment]
Sure. Tried Version 6.0b2. Still no go. Disabled all other plugins, reset all the settings. Not even able to configure the crawler-settings (hoping that a valid sitemap etc maybe would help)..

![image](https://github.com/litespeedtech/lscache_wp/assets/17141205/316e8ca1-2916-4901-baf0-778fbfc907d2)

Let my know if there's anything else I can do to troubleshoot.
